id: IC55716CA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T02:57:15+00:00'
last_modified: '2022-06-08T09:49:38.170834+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ8063
  title: མངོན་པ་མཛོད་ཀྱི་བརྗེད་བྱང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    664E:
      image_group_id: I1PD96636
      title: ''
      total_pages: 18
      order: 1
      base_file: 664E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
