id: P009270
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:30:54.461888
source_metadata:
  id: bdr:W2CZ8063
  title: མངོན་པ་མཛོད་ཀྱི་བརྗེད་བྱང་
  author: ''
  volumes:
    815faf3c0f2e43ceb8ecda0babfbf925:
      image_group_id: I1PD96636
      title: ''
      volume_number: 1
      total_pages: 18
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
