id: P009270
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ8063
  title: མངོན་པ་མཛོད་ཀྱི་བརྗེད་བྱང་
  author: ''
  volumes:
    815faf3c0f2e43ceb8ecda0babfbf925:
      image_group_id: I1PD96636
      title: ''
      volume_number: 1
      total_pages: 18
